version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 908027385477.dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_URI=908027385477.dkr.ecr.us-east-1.amazonaws.com/neupane-sudip-flask-app
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:latest
  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push $REPOSITORY_URI:latest

artifacts:
  files: []
